language: ruby
cache: bundler
rvm:
  - 2.1.1
bundler_args: --without production staging development
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database cortex_test;' -U postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rake cortex:create_categories
  - bundle exec rake spec
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 6cedeabef4da2bf513d1b1a89e48b9ea36535f91b4fcd1420bbdcf7b765fdc49
services:
  - elasticsearch
  - mongodb
  - redis-server
notifications:
  hipchat: 31ca9ff739b018ecd38b1f133947e4@Developers
deploy:
  - provider: cloud66
    master:
    redeployment_hook: https://hooks.cloud66.com/stacks/redeploy/78f9fff824b52e6771109239804d0682/b7cbba409a70314651a4da8e7551fbab
    on: develop
    edge: true
  - provider: cloud66
    master:
    redeployment_hook: https://hooks.cloud66.com/stacks/redeploy/78f9fff824b52e6771109239804d0682/fde5a72f14c83c41bc72fbad298a7e84
    on: master
    edge: true
