sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.0
before_install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch -d -D es.path.data=/tmp -D es.discovery.zen.ping.multicast.enabled=false

  - gem update --system
  - gem update bundler
  - bundle install
  - gem --version
  - npm install -g bower
bundler_args: "--without production staging development"
before_script:
  - sleep 10
  - psql -c 'create database cortex_test;' -U postgres
  - bundle exec rake db:schema:load db:seed cortex:create_categories
  - bundle exec rake cortex:rebuild_indexes
  - bundle exec rake bower:install:development
script:
  - bundle exec rspec --format doc
addons:
  postgresql: '9.4'
  apt:
    packages:
      - jpegoptim
services:
  - redis-server
env:
  global:
  - APP_SECRET=180d0b7491b1f574801b62853532775a60d58a0cdf1ef2848967618e507e94b72e3d1223c3c2ab8fde641aff237774a72c6c3a5cf541b4baba2ff70fd97d121a
  - DEVISE_SECRET=88e9dfa013e8b4f99ecd0470cdbf76709856db22a14b4e2e3576f75809e7054e743c5b2b9fce196f979acf5c64d55ce9c1a26cf542bb73abaa2aa80acc9c040d
  - HOST=http://localhost:3000
  - SMTP_SENDER_DOMAIN=cbcortex.com
  - SMTP_SENDER_ADDRESS=noreply@cbcortex.com
  - ONET_VERSION=18.1
  - MEDIA_MAX_SIZE_MB=100
  - CORS_ALLOWED_ORIGINS=http://localhost:3001
  - ES_VERSION=2.3.1
  - secure: kWX87Atpm82EyyD2EMIhHGZ3ohzR8qDvrEs3Ngwu2Lj1gDgAYvMyMHfcuVwgRmff80ecKYsL/LGFiwHQqO9zF9eizddNYnjS1jF4fS+vsDge0nN/t+5fw3i3jvAA8demU6HOTui9o/NhaBGg48S6OdBJQVuMtJAqFTa2ACXVnq4=
notifications:
  slack: content-enablement:RrrMy3rTrLeNbbYroapZC3Sf
  email: false
deploy:
  - provider: cloud66
    master:
      redeployment_hook: https://hooks.cloud66.com/stacks/redeploy/78f9fff824b52e6771109239804d0682/636db734bafc92081507c7b7e86c0f01
      on: develop
      edge: true
  - provider: cloud66
    master:
      redeployment_hook: https://hooks.cloud66.com/stacks/redeploy/78f9fff824b52e6771109239804d0682/9bdf5cb0fdfa117c6bfeea7d17c20e6a
      on: master
      edge: true
