defaults: &defaults
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'postgresql' %>
  encoding: <%= ENV['DATABASE_ENCODING'] || 'utf8' %>
  reconnect: <%= ENV['DATABASE_RECONNECT'] || 'true' %>
  database: <%= ENV['DATABASE_NAME'] || 'cortex_dev' %>
  pool: <%= ENV['DATABASE_POOL'] || '5' %>
  username: cortex
  host: <%= ENV['DATABASE_HOST'] || '' %>
  port: <%= ENV['DATABASE_PORT'] || '' %>

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
