defaults: &defaults
    default_subdomain: development
    allowed_origins:
      - 'localhost:3000'
      - 'localhost:63342'
      - 'whump.net'

development:
    <<: *defaults

test:
    <<: *defaults

production:
    <<: *defaults
    default_subdomain: public