development: &defaults
  cortex:
    api:
      base_url: <%= ENV['CORTEX_API_BASE_URL'] %>
      version: <%= ENV['CORTEX_API_VERSION'] %>
  extra:
    google_analytics_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
  cors:
    allowed_origins: <%= ENV['CORS_ALLOWED_ORIGINS'] %>
    allowed_origins_regex: <%= ENV['CORS_ALLOWED_ORIGINS_REGEX'] %>
  media:
    max_size_mb: <%= ENV['MEDIA_MAX_SIZE_MB'] || 100 %>
  onet:
    version: <%= ENV['ONET_VERSION'] || '18.1' %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
