defaults: &defaults
  extra: {}
  default_page_size: 25
  default_subdomain: public
  allowed_origins:
    - 'localhost:3000'
    - 'localhost:3001'
    - 'cbcortex.com'
  allowed_origins_regex:
    - '.+\.cbcortex\.com'
  media:
    max_size_mb: 100
  onet:
    version: '18.1'

test:
  <<: *defaults

development:
  <<: *defaults

local:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
