development: &defaults
  extra:
    google_analytics_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
  cors:
    allowed_origins: <%= ENV['CORS_ALLOWED_ORIGINS'] %>
    allowed_origins_regex: <%= ENV['CORS_ALLOWED_ORIGINS_REGEX'] %>
  media:
    max_size_mb: <%= ENV['MEDIA_MAX_SIZE_MB'] || 100 %>
  onet:
    version: <%= ENV['ONET_VERSION'] || '18.1' %>
  jargon:
    client_id: <%= ENV['JARGON_CLIENT_ID'] %>
    client_secret: <%= ENV['JARGON_CLIENT_SECRET'] %>
    site_url: <%= ENV['JARGON_SITE_URL'] %>
    username: <%= ENV['JARGON_USERNAME'] %>
    password: <%= ENV['JARGON_PASSWORD'] %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
