defaults: &defaults
  default_page_size: 25
  default_subdomain: public
  allowed_origins:
    - 'localhost:3000'
    - 'localhost:63342'
    - 'whump.net'
  assets:
    max_size_mb: 100
    allowed_media_types:
      - type: image/jpeg
        thumb: True
      - type: image/jpg
        thumb: True
      - type: image/pjpeg
        thumb: True
      - type: image/png
        thumb: True
      - type: image/gif
        thumb: True
      - type: image/bmp
        thumb: True
      - type: image/x-png
        thumb: True
      - type: application/pdf
        thumb: True
      - type: application/vnd.ms-excel
      - type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      - type: application/msword
      - type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - type: text/plain
      - type: application/zip
      - type: video/avi
      - type: video/msvideo
      - type: video/x-msvideo
      - type: video/quicktime
      - type: video/mp4
      - type: audio/mpeg
      - type: audio/mp3
      - type: audio/x-mp3
      - type: audio/mpeg3
      - type: audio/x-mpeg3
      - type: audio/mpg

test:
  <<: *defaults

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
