defaults: &defaults
  default_subdomain: public
  allowed_origins:
    - 'localhost:3000'
    - 'localhost:63342'
    - 'whump.net'

development:
  <<: *defaults

test:
  default_subdomain: public
  <<: *defaults

production:
  <<: *defaults
  default_subdomain: public