defaults: &defaults
  default_subdomain: public
  allowed_origins:
    - 'localhost:3000'
    - 'localhost:63342'
    - 'whump.net'
  assets:
    max_size_mb: 100
    allowed_media_types:
      - type: image/jpeg
        thumbnail: True
      - type: image/jpg
        thumbnail: True
      - type: image/pjpeg
        thumbnail: True
      - type: image/png
        thumbnail: True
      - type: image/gif
        thumbnail: True
      - type: image/bmp
        thumbnail: True
      - type: image/x-png
        thumbnail: True
      - type: application/pdf
        thumbnail: True
      - type: application/vnd.ms-excel
      - type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      - type: application/msword
      - type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - type: text/plain
      - type: application/zip
      - type: video/x-msvideo
      - type: video/quicktime
      - type: video/mp4

test:
  <<: *defaults

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
