default: &default
  adapter: postgresql
  encoding: unicode
  user: cortex
  pool: 5
  timeout: 5000

local:
  <<: *default
  database: cortex_dev

development:
  <<: *default
  database: cortex_dev

test:
  <<: *default
  database: cortex_test

production:
  <<: *default
  database: cortex
