development:
  adapter: postgresql
  encoding: unicode
  database: cortex_dev
  user: cortex
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: cortex_test
  user: cortex
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: cb-cortex-db
  pool: 5
  password:

