defaults: &defaults
  sessions:
    default:
      database: <%= ENV['MONGODB_DATABASE'] || 'cortex_dev' %>
      hosts:
        - <%= "#{ENV['MONGODB_HOST'] || 'localhost'}:#{ENV['MONGODB_PORT'] || 27017}" %>

test:
  sessions:
    default:
      database: <%= ENV['TEST_MONGODB_DATABASE'] || 'cortex_test' %>
      hosts:
        - <%= "#{ENV['TEST_MONGODB_HOST'] || 'localhost'}:#{ENV['TEST_MONGODB_PORT'] || 27017}" %>

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
